version: 2
updates:
  - package-ecosystem: "npm"
    directories:
      - "/packages/cli-hooks"
      - "/packages/cli-test"
      - "/packages/logger"
      - "/packages/oauth"
      - "/packages/socket-mode"
      - "/packages/types"
      - "/packages/web-api"
      - "/packages/web-api/test/integration-tests/**"
    groups:
      devDependencies:
        dependency-type: "development"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "@typescript-eslint/parser"
      - dependency-name: "@typescript-eslint/eslint-plugin"
    open-pull-requests-limit: 10
  - package-ecosystem: "npm"
    directories:
      - "/"
      - "/docs"
      - "/examples/*"
    schedule:
      interval: "monthly"
    groups:
      docusaurus:
        patterns:
          - "@docusaurus/*"
      slack:
        patterns:
          - "@slack/*"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
