/////////////////////////////////////////////////////////////////////////////////////////
//                                                                                     //
// !!! DO NOT EDIT THIS FILE !!!                                                       //
//                                                                                     //
// This file is auto-generated by scripts/generate-web-api-types.sh in the repository. //
// Please refer to the script code to learn how to update the source data.             //
//                                                                                     //
/////////////////////////////////////////////////////////////////////////////////////////

import type { WebAPICallResult } from '../../WebClient';
export type AdminWorkflowsCollaboratorsRemoveResponse = WebAPICallResult & {
  error?: string;
  errors?: Error[];
  needed?: string;
  ok?: boolean;
  provided?: string;
};

export interface Error {
  message?: string;
  user?: string;
  workflow?: string;
}
