/* eslint-disable */
/////////////////////////////////////////////////////////////////////////////////////////
//                                                                                     //
// !!! DO NOT EDIT THIS FILE !!!                                                       //
//                                                                                     //
// This file is auto-generated by scripts/generate-web-api-types.sh in the repository. //
// Please refer to the script code to learn how to update the source data.             //
//                                                                                     //
/////////////////////////////////////////////////////////////////////////////////////////

import type { WebAPICallResult } from '../../WebClient';
export type AdminAppsConfigLookupResponse = WebAPICallResult & {
  configs?: Config[];
  error?: string;
  needed?: string;
  ok?: boolean;
  provided?: string;
  response_metadata?: ResponseMetadata;
};

export interface Config {
  app_id?: string;
  domain_restrictions?: DomainRestrictions;
  workflow_auth_strategy?: string;
}

export interface DomainRestrictions {
  emails?: string[];
  urls?: string[];
}

export interface ResponseMetadata {
  messages?: string[];
}
