/////////////////////////////////////////////////////////////////////////////////////////
//                                                                                     //
// !!! DO NOT EDIT THIS FILE !!!                                                       //
//                                                                                     //
// This file is auto-generated by scripts/generate-web-api-types.sh in the repository. //
// Please refer to the script code to learn how to update the source data.             //
//                                                                                     //
/////////////////////////////////////////////////////////////////////////////////////////

import type { WebAPICallResult } from '../../WebClient';
export type AdminUsersSessionGetSettingsResponse = WebAPICallResult & {
  error?: string;
  needed?: string;
  no_settings_applied?: string[];
  ok?: boolean;
  provided?: string;
  session_settings?: SessionSetting[];
};

export interface SessionSetting {
  desktop_app_browser_quit?: boolean;
  duration?: number;
  user_id?: string;
}
