/////////////////////////////////////////////////////////////////////////////////////////
//                                                                                     //
// !!! DO NOT EDIT THIS FILE !!!                                                       //
//                                                                                     //
// This file is auto-generated by scripts/generate-web-api-types.sh in the repository. //
// Please refer to the script code to learn how to update the source data.             //
//                                                                                     //
/////////////////////////////////////////////////////////////////////////////////////////

import type { WebAPICallResult } from '../../WebClient';
export type AgentsConversationsGetCanvasResponse = WebAPICallResult & {
  canvas_id?: string;
  comments?: Comment[];
  content?: string;
  error?: string;
  has_more_comments?: boolean;
  needed?: string;
  ok?: boolean;
  provided?: string;
  title?: string;
  warning?: string;
};

export interface Comment {
  has_more_replies?: boolean;
  id?: string;
  is_resolved?: boolean;
  quoted_text?: string;
  replies?: Reply[];
  text?: string;
  ts?: string;
  user_id?: string;
}

export interface Reply {
  text?: string;
  ts?: string;
  user_id?: string;
}
