/////////////////////////////////////////////////////////////////////////////////////////
//                                                                                     //
// !!! DO NOT EDIT THIS FILE !!!                                                       //
//                                                                                     //
// This file is auto-generated by scripts/generate-web-api-types.sh in the repository. //
// Please refer to the script code to learn how to update the source data.             //
//                                                                                     //
/////////////////////////////////////////////////////////////////////////////////////////

import type { WebAPICallResult } from '../../WebClient';
export type AgentsConversationsGetCanvasResponse = WebAPICallResult & {
  canvas_id?: string;
  comments?: any[];
  content?: string;
  error?: string;
  has_more_comments?: boolean;
  needed?: string;
  ok?: boolean;
  provided?: string;
  title?: string;
  warning?: string;
};
