/////////////////////////////////////////////////////////////////////////////////////////
//                                                                                     //
// !!! DO NOT EDIT THIS FILE !!!                                                       //
//                                                                                     //
// This file is auto-generated by scripts/generate-web-api-types.sh in the repository. //
// Please refer to the script code to learn how to update the source data.             //
//                                                                                     //
/////////////////////////////////////////////////////////////////////////////////////////

import { WebAPICallResult } from '../../WebClient';
export type AppsEventAuthorizationsListResponse = WebAPICallResult & {
  authorizations?: Authorization[];
  error?:          string;
  needed?:         string;
  ok?:             boolean;
  provided?:       string;
};

export interface Authorization {
  enterprise_id?:         string;
  is_bot?:                boolean;
  is_enterprise_install?: boolean;
  team_id?:               string;
  user_id?:               string;
}
