/////////////////////////////////////////////////////////////////////////////////////////
//                                                                                     //
// !!! DO NOT EDIT THIS FILE !!!                                                       //
//                                                                                     //
// This file is auto-generated by scripts/generate-web-api-types.sh in the repository. //
// Please refer to the script code to learn how to update the source data.             //
//                                                                                     //
/////////////////////////////////////////////////////////////////////////////////////////

import type { WebAPICallResult } from '../../WebClient';
export type AssistantSearchInfoResponse = WebAPICallResult & {
  error?: string;
  is_ai_search_enabled?: boolean;
  needed?: string;
  ok?: boolean;
  provided?: string;
  warning?: string;
};
