/* eslint-disable */
/////////////////////////////////////////////////////////////////////////////////////////
//                                                                                     //
// !!! DO NOT EDIT THIS FILE !!!                                                       //
//                                                                                     //
// This file is auto-generated by scripts/generate-web-api-types.sh in the repository. //
// Please refer to the script code to learn how to update the source data.             //
//                                                                                     //
/////////////////////////////////////////////////////////////////////////////////////////

import { WebAPICallResult } from '../../WebClient';
export type CanvasesSectionsLookupResponse = WebAPICallResult & {
  acceptedScopes?:    string[];
  ok?:                boolean;
  response_metadata?: ResponseMetadata;
  sections?:          Section[];
};

export interface ResponseMetadata {
  scopes?: string[];
}

export interface Section {
  id?: string;
}
