/////////////////////////////////////////////////////////////////////////////////////////
//                                                                                     //
// !!! DO NOT EDIT THIS FILE !!!                                                       //
//                                                                                     //
// This file is auto-generated by scripts/generate-web-api-types.sh in the repository. //
// Please refer to the script code to learn how to update the source data.             //
//                                                                                     //
/////////////////////////////////////////////////////////////////////////////////////////

import type { WebAPICallResult } from '../../WebClient';
export type ConversationsAcceptSharedInviteResponse = WebAPICallResult & {
  can_open_scdm?: boolean;
  channel_id?: string;
  error?: string;
  implicit_approval?: boolean;
  invite_id?: string;
  needed?: string;
  ok?: boolean;
  provided?: string;
};
