/* eslint-disable */
/////////////////////////////////////////////////////////////////////////////////////////
//                                                                                     //
// !!! DO NOT EDIT THIS FILE !!!                                                       //
//                                                                                     //
// This file is auto-generated by scripts/generate-web-api-types.sh in the repository. //
// Please refer to the script code to learn how to update the source data.             //
//                                                                                     //
/////////////////////////////////////////////////////////////////////////////////////////

import type { WebAPICallResult } from '../../WebClient';
export type RemindersAddResponse = WebAPICallResult & {
  error?: string;
  needed?: string;
  ok?: boolean;
  provided?: string;
  reminder?: Reminder;
  response_metadata?: ResponseMetadata;
};

export interface Reminder {
  complete_ts?: number;
  creator?: string;
  id?: string;
  recurring?: boolean;
  text?: string;
  time?: number;
  user?: string;
}

export interface ResponseMetadata {
  messages?: string[];
}
