/////////////////////////////////////////////////////////////////////////////////////////
//                                                                                     //
// !!! DO NOT EDIT THIS FILE !!!                                                       //
//                                                                                     //
// This file is auto-generated by scripts/generate-web-api-types.sh in the repository. //
// Please refer to the script code to learn how to update the source data.             //
//                                                                                     //
/////////////////////////////////////////////////////////////////////////////////////////

import type { WebAPICallResult } from '../../WebClient';
export type SlackListsCreateResponse = WebAPICallResult & {
  error?: string;
  list_id?: string;
  list_metadata?: ListMetadata;
  needed?: string;
  ok?: boolean;
  provided?: string;
  warning?: string;
};

export interface ListMetadata {
  schema?: Schema[];
  subtask_schema?: SubtaskSchema[];
}

export interface Schema {
  id?: string;
  is_primary_column?: boolean;
  key?: string;
  name?: string;
  options?: SchemaOptions;
  type?: string;
}

export interface SchemaOptions {
  choices?: Choice[];
  format?: string;
  show_member_name?: boolean;
}

export interface Choice {
  color?: string;
  label?: string;
  value?: string;
}

export interface SubtaskSchema {
  id?: string;
  is_primary_column?: boolean;
  key?: string;
  name?: string;
  options?: SubtaskSchemaOptions;
  type?: string;
}

export interface SubtaskSchemaOptions {
  format?: string;
  show_member_name?: boolean;
}
