/////////////////////////////////////////////////////////////////////////////////////////
//                                                                                     //
// !!! DO NOT EDIT THIS FILE !!!                                                       //
//                                                                                     //
// This file is auto-generated by scripts/generate-web-api-types.sh in the repository. //
// Please refer to the script code to learn how to update the source data.             //
//                                                                                     //
/////////////////////////////////////////////////////////////////////////////////////////

import type { WebAPICallResult } from '../../WebClient';
export type WorkflowsFeaturedListResponse = WebAPICallResult & {
  error?: string;
  featured_workflows?: FeaturedWorkflow[];
  invalid_channel_ids?: string[];
  needed?: string;
  ok?: boolean;
  provided?: string;
  warning?: string;
};

export interface FeaturedWorkflow {
  channel_id?: string;
  triggers?: Trigger[];
}

export interface Trigger {
  id?: string;
  title?: string;
}
