/* eslint-disable */
/////////////////////////////////////////////////////////////////////////////////////////
//                                                                                     //
// !!! DO NOT EDIT THIS FILE !!!                                                       //
//                                                                                     //
// This file is auto-generated by scripts/generate-web-api-types.sh in the repository. //
// Please refer to the script code to learn how to update the source data.             //
//                                                                                     //
/////////////////////////////////////////////////////////////////////////////////////////

import { WebAPICallResult } from '../WebClient';
export type AdminConversationsGetConversationPrefsResponse = WebAPICallResult & {
  error?:    string;
  needed?:   string;
  ok?:       boolean;
  prefs?:    Prefs;
  provided?: string;
};

export interface Prefs {
  can_thread?:   CanThread;
  who_can_post?: CanThread;
}

export interface CanThread {
  type?: string[];
  user?: string[];
}
