/* eslint-disable */
/////////////////////////////////////////////////////////////////////////////////////////
//                                                                                     //
// !!! DO NOT EDIT THIS FILE !!!                                                       //
//                                                                                     //
// This file is auto-generated by scripts/generate-web-api-types.sh in the repository. //
// Please refer to the script code to learn how to update the source data.             //
//                                                                                     //
/////////////////////////////////////////////////////////////////////////////////////////

import { WebAPICallResult } from '../WebClient';
export type AdminConversationsInviteResponse = WebAPICallResult & {
  ok?:              boolean;
  error?:           string;
  failed_user_ids?: FailedUserids;
  needed?:          string;
  provided?:        string;
};

export interface FailedUserids {
  U00000000?: string;
  U00000001?: string;
}
