/* tslint:disable */
/////////////////////////////////////////////////////////////////////////////////////////
//                                                                                     //
// !!! DO NOT EDIT THIS FILE !!!                                                       //
//                                                                                     //
// This file is auto-generated by scripts/generate-web-api-types.sh in the repository. //
// Please refer to the script code to learn how to update the soruce data.             //
//                                                                                     //
/////////////////////////////////////////////////////////////////////////////////////////

import { WebAPICallResult } from '../WebClient';
export type FilesCommentsEditResponse = WebAPICallResult & {
  ok?:       boolean;
  comment?:  Comment;
  error?:    string;
  needed?:   string;
  provided?: string;
};

export interface Comment {
  id?:        string;
  created?:   number;
  timestamp?: number;
  user?:      string;
  is_intro?:  boolean;
  comment?:   string;
}
