/* tslint:disable */
/////////////////////////////////////////////////////////////////////////////////////////
//                                                                                     //
// !!! DO NOT EDIT THIS FILE !!!                                                       //
//                                                                                     //
// This file is auto-generated by scripts/generate-web-api-types.sh in the repository. //
// Please refer to the script code to learn how to update the source data.             //
//                                                                                     //
/////////////////////////////////////////////////////////////////////////////////////////

import { WebAPICallResult } from '../WebClient';
export type ImListResponse = WebAPICallResult & {
  ok?:                boolean;
  ims?:               Im[];
  warning?:           string;
  response_metadata?: ResponseMetadata;
  error?:             string;
  needed?:            string;
  provided?:          string;
};

export interface Im {
  id?:              string;
  created?:         number;
  is_archived?:     boolean;
  is_im?:           boolean;
  is_org_shared?:   boolean;
  user?:            string;
  is_user_deleted?: boolean;
  priority?:        number;
}

export interface ResponseMetadata {
  next_cursor?: string;
  messages?:    string[];
  warnings?:    string[];
}
