/* tslint:disable */
/////////////////////////////////////////////////////////////////////////////////////////
//                                                                                     //
// !!! DO NOT EDIT THIS FILE !!!                                                       //
//                                                                                     //
// This file is auto-generated by scripts/generate-web-api-types.sh in the repository. //
// Please refer to the script code to learn how to update the soruce data.             //
//                                                                                     //
/////////////////////////////////////////////////////////////////////////////////////////

import { WebAPICallResult } from '../WebClient';
export type MigrationExchangeResponse = WebAPICallResult & {
  ok?:               boolean;
  warning?:          string;
  error?:            string;
  needed?:           string;
  provided?:         string;
  team_id?:          string;
  enterprise_id?:    string;
  invalid_user_ids?: string[];
  user_id_map?:      UseridMap;
};

export interface UseridMap {
}
