/* eslint-disable */
/////////////////////////////////////////////////////////////////////////////////////////
//                                                                                     //
// !!! DO NOT EDIT THIS FILE !!!                                                       //
//                                                                                     //
// This file is auto-generated by scripts/generate-web-api-types.sh in the repository. //
// Please refer to the script code to learn how to update the source data.             //
//                                                                                     //
/////////////////////////////////////////////////////////////////////////////////////////

import { WebAPICallResult } from '../WebClient';
export type RtmConnectResponse = WebAPICallResult & {
  ok?:       boolean;
  url?:      string;
  team?:     Team;
  self?:     Self;
  error?:    string;
  needed?:   string;
  provided?: string;
};

export interface Self {
  id?:   string;
  name?: string;
}

export interface Team {
  id?:     string;
  name?:   string;
  domain?: string;
}
