/* eslint-disable */
/////////////////////////////////////////////////////////////////////////////////////////
//                                                                                     //
// !!! DO NOT EDIT THIS FILE !!!                                                       //
//                                                                                     //
// This file is auto-generated by scripts/generate-web-api-types.sh in the repository. //
// Please refer to the script code to learn how to update the source data.             //
//                                                                                     //
/////////////////////////////////////////////////////////////////////////////////////////

import { WebAPICallResult } from '../WebClient';
export type TeamProfileGetResponse = WebAPICallResult & {
  error?:    string;
  needed?:   string;
  ok?:       boolean;
  profile?:  Profile;
  provided?: string;
};

export interface Profile {
  fields?:   Field[];
  sections?: Section[];
}

export interface Field {
  field_name?:      string;
  hint?:            string;
  id?:              string;
  is_hidden?:       boolean;
  label?:           string;
  ordering?:        number;
  possible_values?: string[];
  type?:            string;
}

export interface Section {
  id?:           string;
  is_hidden?:    boolean;
  label?:        string;
  order?:        number;
  section_type?: string;
  team_id?:      string;
}
