/* eslint-disable */
/////////////////////////////////////////////////////////////////////////////////////////
//                                                                                     //
// !!! DO NOT EDIT THIS FILE !!!                                                       //
//                                                                                     //
// This file is auto-generated by scripts/generate-web-api-types.sh in the repository. //
// Please refer to the script code to learn how to update the source data.             //
//                                                                                     //
/////////////////////////////////////////////////////////////////////////////////////////

import { WebAPICallResult } from '../WebClient';
export type TeamProfileGetResponse = WebAPICallResult & {
  ok?:       boolean;
  profile?:  Profile;
  error?:    string;
  needed?:   string;
  provided?: string;
};

export interface Profile {
  fields?: Field[];
}

export interface Field {
  id?:         string;
  ordering?:   number;
  field_name?: string;
  label?:      string;
  hint?:       string;
  type?:       string;
  is_hidden?:  boolean;
}
