/* tslint:disable */
/////////////////////////////////////////////////////////////////////////////////////////
//                                                                                     //
// !!! DO NOT EDIT THIS FILE !!!                                                       //
//                                                                                     //
// This file is auto-generated by scripts/generate-web-api-types.sh in the repository. //
// Please refer to the script code to learn how to update the source data.             //
//                                                                                     //
/////////////////////////////////////////////////////////////////////////////////////////

import { WebAPICallResult } from '../WebClient';
export type UsersGetPresenceResponse = WebAPICallResult & {
  ok?:               boolean;
  warning?:          string;
  error?:            string;
  needed?:           string;
  provided?:         string;
  presence?:         string;
  online?:           boolean;
  auto_away?:        boolean;
  manual_away?:      boolean;
  connection_count?: number;
  last_activity?:    number;
};
