module.exports = {
  ApiFacet: require('./api.js'),
  AuthFacet: require('./auth.js'),
  ChannelsFacet: require('./channels.js'),
  ChatFacet: require('./chat.js'),
  DmFacet: require('./dm.js'),
  EmojiFacet: require('./emoji.js'),
  FilesFacet: require('./files.js'),
  GroupsFacet: require('./groups.js'),
  OauthFacet: require('./oauth.js'),
  PinsFacet: require('./pins.js'),
  PresenceFacet: require('./presence.js'),
  ReactionsFacet: require('./reactions.js'),
  RtmFacet: require('./rtm.js'),
  SearchFacet: require('./search.js'),
  StarsFacet: require('./stars.js'),
  TeamFacet: require('./team.js'),
  UsersFacet: require('./users.js'),
};
