module.exports = {
  ApiFacet: require('./api.js'),
  AuthFacet: require('./auth.js'),
  BotsFacet: require('./bots'),
  ChannelsFacet: require('./channels.js'),
  ChatFacet: require('./chat.js'),
  DndFacet: require('./dnd.js'),
  EmojiFacet: require('./emoji.js'),
  FilesFacet: require('./files.js'),
  FilesCommentsFacet: require('./files.comments.js'),
  GroupsFacet: require('./groups.js'),
  ImFacet: require('./im'),
  MpimFacet: require('./mpim.js'),
  OauthFacet: require('./oauth.js'),
  PinsFacet: require('./pins.js'),
  PresenceFacet: require('./presence.js'),
  ReactionsFacet: require('./reactions.js'),
  RemindersFacet: require('./reminders.js'),
  RtmFacet: require('./rtm.js'),
  SearchFacet: require('./search.js'),
  StarsFacet: require('./stars.js'),
  TeamFacet: require('./team.js'),
  UsergroupsFacet: require('./usergroups.js'),
  UsergroupsUsersFacet: require('./usergroups.users.js'),
  UsersFacet: require('./users.js')
};
