name: deno.land Continuous Deployment

on:
  push:
    tags:
      - '@slack/web-api*'

defaults:
  run:
    shell: bash
    working-directory: packages/web-api

jobs:
  transpile:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - name: Echo Tag Name
      run: echo "$GITHUB_REF_NAME"
    - uses: actions/checkout@v2
      with:
        # pull all tags/branches with full history;
        # need that to checkout different branch and push artifacts later
        fetch-depth: 0
    - name: Set up Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 16
    - name: Inject browser field and add dependencies to package.json
      run: |
        perl -pi.bak -e 's/"tsd": {/"browser":{"os":"os-browserify","path":"path-browserify","querystring":".\/deno-shims\/qs-shim.js"},"tsd": {/g' package.json
        perl -pi.bak -e 's/"axios": /"path-browserify":"1.0.1","os-browserify":"0.3.0","axios": /g' package.json
    - run: npm install
    - run: npm run build:deno
    - run: mv mod.js ../../.
    - name: Commit and tag built artifact to separate branch
      run: |
        git config user.name slack-cicd
        git config user.email github-cicd@slack.com
        git checkout -- package.json
        git checkout deno-web-api
        mv ../../mod.js .
        git add mod.js
        git commit -m "Adding transpiled deno ${GITHUB_REF_NAME} release artifact."
        git tag "deno/${GITHUB_REF_NAME}"
        git push --tags
